# Acknowledgement

https://github.com/zekelabs/data-science-complete-tutorial



# 1. Introduction to Numpy
Numpy is a Library in python that specializes in dealing with multidimensional Arrays. The cool features of Numpy are
* **Automatic Checking :** Numpy ndArrays automatically check the consistancy of data. For instance, it is not possible to have 1st row with 2 elements and 2nd row with 3 elements
* **Contiguous Storage :** Unlike Python Lists, Numpy stores the data in contiguous Memory Locations, leading to lesser Space
* **Faster Vector Arithmatics :** Because of contiguous storage, the operations are performed faster as compared to default Python Execution for Lists

In [1]:
# Importing Numpy
import numpy as np

## 1.1 Initialization of 1D array in Python
A numpy array comes with 2 important state variables. Just like Python, it automatically detects dtype (if not mentioned)
* dtype
* shape

#### 1.1.1 Initialization from python List
numpy.array( list **)**


In [2]:
# Initializing from Python List
v = np.array([1,4,9,3,2, 2020.617])
print ('1D array in numpy is %s\n'%v)
print ('dtype of the numpy array is %s\n'%str(v.dtype))
print ('shape of the numpy array is %s\n'%v.shape)

1D array in numpy is [1.000000e+00 4.000000e+00 9.000000e+00 3.000000e+00 2.000000e+00
 2.020617e+03]

dtype of the numpy array is float64

shape of the numpy array is 6



#### 1.1.2 Initialization via arange
numpy.arange(**\[**start, **\]**stop, **\[**step, **\]** dtype=None)

In [3]:
v1 = np.arange(3)
print ('Creating a numpy array via arange (stop=5) : %s\n'%v1)
v2 = np.arange(2,4)
print ('Creating a numpy array via arange (start=2,stop=5) : %s\n'%v2)
v3 = np.arange(0,-8,-2)
print ('Creating a numpy array via arange (start=0,stop=-10,step=-2) : %s\n'%v3)



Creating a numpy array via arange (stop=5) : [0 1 2]

Creating a numpy array via arange (start=2,stop=5) : [2 3]

Creating a numpy array via arange (start=0,stop=-10,step=-2) : [ 0 -2 -4 -6]



## 1.2. Initialization of 2D array in Python
When we talk about 2D array, it is important to note that Numpy stores Matrix is ***Row Major Format***. Row major format means that the the complete row will be stored first and then the next row will be stored and so on. You can choose to store a matrix in colum major format by mentioning ***order='F'*** on ndarray creation, which means ***Column Major Format***  or *Fortran Style Format*. 


#### 1.2.1 Initialization from List of List
numpy.array **(** ***object***, dtype=None **)**

Here the matrix that we have taken is 
$$mat = \begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$$

#### 1.2.2 Initialization with zero/ones
numpy.**zeros**(*shape*, dtype=float)  
numpy.**ones**(*shape*, dtype=float)

In [4]:
mat_zeros = np.zeros(shape=(3,2))
print ('Zeros Matris of shape %s is \n%s\n'%(mat_zeros.shape,mat_zeros))
mat_ones = np.ones(shape=(2,3))
print ('Ones Matris of shape %s is \n%s\n'%(mat_ones.shape,mat_ones))


Zeros Matris of shape (3, 2) is 
[[0. 0.]
 [0. 0.]
 [0. 0.]]

Ones Matris of shape (2, 3) is 
[[1. 1. 1.]
 [1. 1. 1.]]



#### 1.2.3 Initialization with Random Values
**1.2.3.1** numpy.**random.random**(*size=None*,)  
**1.2.3.2** numpy.**random.randint**(low, high, *size=None*, dtype='I') : The value of matrix lies between low and high-1  
**1.2.3.3** numpy.**random.randn**($d_0,d_1,\cdots,d_n$)


In [5]:
#Using numpy.random.random
mat1 = np.random.random(size=(3,3))
print ('matrix generated from numpy.random.random is \n%s\n'%mat1)
mat2 = np.random.randint(low=0,high=2,size=(2,2))
print ('matrix generated from numpy.random.random is \n%s\n'%mat2)
mat3 = np.random.randn(2,4)
print ('matrix generated from numpy.random.randn is \n%s\n'%mat3)


matrix generated from numpy.random.random is 
[[0.89459392 0.85211331 0.6169972 ]
 [0.04084943 0.19261887 0.40276677]
 [0.62782816 0.80875445 0.6416934 ]]

matrix generated from numpy.random.random is 
[[0 1]
 [0 1]]

matrix generated from numpy.random.randn is 
[[-0.40910053 -0.43375763  1.8051687  -1.32044469]
 [ 3.03585136  1.21509848  2.26623711 -1.13984584]]



## 1.3. Slicing and Indexing in Numpy
Just like python, numpy also has 0 indexing. Let us see some of the commonly used slicing techniques .  
* Generic Slicing Operation : \[start\]:\[end\]:\[jump\]
* Only jump    **::2**
* Only end    **:5**
* Start and jump **2::-1**
* End and Jump **:5:2**
* Start, end and jump **2:7:3**


#### 1.3.1 Remove n elements
vec\[:*-n*\]

In [6]:
pymat = [[1,2,3,7],[4,5,6,8]]
npmat = np.array(pymat)
print ('numpy matrix is \n%s\n'%npmat)
print ('Flattened version of numpy matrix is %s\n'%npmat.flatten())
# By flatten the matrix becomes row major 1D vector (This is the way in which a matrix is stored in memory). 


numpy matrix is 
[[1 2 3 7]
 [4 5 6 8]]

Flattened version of numpy matrix is [1 2 3 7 4 5 6 8]



In [7]:
vec = np.arange(17)
vec1 = vec[:-5]
print ('Result of removing last 3 elements from range(10) : \n%s\n'%vec1)

Result of removing last 3 elements from range(10) : 
[ 0  1  2  3  4  5  6  7  8  9 10 11]



#### 1.3.2 Access elements at even indices in a 1D array
vec[::2]

In [8]:

vec1 = np.arange(0,30,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[::2]
print ('Elements at even indices are %s\n'%vec2)


Original array is [ 0  3  6  9 12 15 18 21 24 27]

Elements at even indices are [ 0  6 12 18 24]



#### 1.3.3 Access elements at indices in reverse order
vec[::-1]

In [9]:
vec1 = np.arange(0,10,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[::-1]
print ('Elements for indices in reverse is %s\n'%vec2)

Original array is [0 3 6 9]

Elements for indices in reverse is [9 6 3 0]



#### 1.3.4 Access elements present for a range of indices
vec[a:b]

In [10]:
vec1 = np.arange(0,20,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[2:5]
print ('Elements for indices 2:5 is %s\n'%vec2)

Original array is [ 0  3  6  9 12 15 18]

Elements for indices 2:5 is [ 6  9 12]



#### 1.3.5 Access a particular set of index given by a list
vec[idxlist]

In [11]:
idx=[0,1,5]
vec1 = np.arange(0,20,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[idx]
print ('Subarray constructed by indices %s is %s\n'%(idx,vec2))

Original array is [ 0  3  6  9 12 15 18]

Subarray constructed by indices [0, 1, 5] is [ 0  3 15]



#### 1.3.6 Creating a submatrix

In [12]:
mat = np.random.randint(0,6,(3,3))
# Create a submatrix with first 2 rows and last 2 columns
submat1 = mat[0:2,-2:]
print ('Original Matrix is \n%s\n'%mat)
print ('Sub Matrix with first 2 rows and last 2 columns is \n%s\n'%submat1)
submat2 = mat[:,3:0:-1]
print ('After flipping the columns of the matrix, it looks : \n%s\n'%submat2)

Original Matrix is 
[[4 4 3]
 [5 0 3]
 [4 0 3]]

Sub Matrix with first 2 rows and last 2 columns is 
[[4 3]
 [0 3]]

After flipping the columns of the matrix, it looks : 
[[3 4]
 [3 0]
 [3 0]]



#### 1.3.7 Horizontal Matrix splitting
numpy.**hsplit**(ary, *indices_or_sections*)  
  
hsplit basically splits a matrix across the horizontal plane based on the indices. Do note that the ***number of rows*** always remains ***constant*** in each section after the horizontal splitting.

![](img/1.3.7-hsplit-01.jpg)

In [13]:
mat = np.random.randint(0,6,(3,7))
sp1,sp2,sp3 = np.hsplit(mat,[4,6])
print ('Original matrix of shape %s, is \n%s\n'%(mat.shape,mat))
print ('First split of shape %s, is \n%s\n'%(sp1.shape,sp1))
print ('Second split of shape %s, is \n%s\n'%(sp2.shape,sp2))
print ('Third split of shape %s, is \n%s\n'%(sp3.shape,sp3))

Original matrix of shape (3, 7), is 
[[3 0 2 1 0 5 3]
 [2 4 5 1 0 2 2]
 [4 5 0 4 1 0 3]]

First split of shape (3, 4), is 
[[3 0 2 1]
 [2 4 5 1]
 [4 5 0 4]]

Second split of shape (3, 2), is 
[[0 5]
 [0 2]
 [1 0]]

Third split of shape (3, 1), is 
[[3]
 [2]
 [3]]



#### 1.3.8 Vertical Matrix Splitting
numpy.**vsplit**(ary, *indices_or_sections*)  
  
vsplit is yet another operation which splits the matrix across the vertical plane based on the ***'rowwise split-index array'***. The ***number of columns*** always remain ***constant*** in each split.

In [14]:
mat = np.random.randint(0,6,(3,7))
sp1,sp2 = np.vsplit(mat,[1])
print ('Original matrix of shape %s, is \n%s\n'%(mat.shape,mat))
print ('First split of shape %s, is \n%s\n'%(sp1.shape,sp1))
print ('Second split of shape %s, is \n%s\n'%(sp2.shape,sp2))

Original matrix of shape (3, 7), is 
[[1 3 4 0 1 5 5]
 [0 3 3 5 1 2 4]
 [2 3 2 5 3 5 0]]

First split of shape (1, 7), is 
[[1 3 4 0 1 5 5]]

Second split of shape (2, 7), is 
[[0 3 3 5 1 2 4]
 [2 3 2 5 3 5 0]]



> ### *Class Examples for 1.1 to 1.3*
>
> 1. Create a matrix of size (2,3) with random binary values
> 2. Find the sum of all 2x2 blocks (overlapping) for a random integer matrix of size (3,5) 

## 1.4. Understanding - Pass By Reference 
Just like python lists, Numpy also exhibits default pass-by-reference behavior


In [15]:
mat1 = np.random.random((2,3))
pt1 = mat1[0].__array_interface__['data'][0]
print ('Memory Location of mat1[0] is : %s\n'%pt1)
pt2 = mat1[1].__array_interface__['data'][0]
print ('Memory Location of mat1[1] is : %s\n'%pt2)
print ('Difference in Memory Location for 3 elements  is : %s bytes\n'%(pt2-pt1))
print ('Memory jump = 8 bytes')


Memory Location of mat1[0] is : 105553161125936

Memory Location of mat1[1] is : 105553161125960

Difference in Memory Location for 3 elements  is : 24 bytes

Memory jump = 8 bytes


#### 1.4.1 Experiment : Change the value of array by Reference

In [16]:
def identity(elem):
    return elem
v = np.array([1,2,3])
v1 = v # Copy by reference
v1[0]=10
print ('Value of v, after v1 is modified is %s\n'%v)
# Pass by Function 
v = np.array([1,2,3])
v1 = identity(v) # Copy by reference
v1[0]=10
print ('Value of v after func(v) is modified is %s\n'%v)
v = np.array([1,2,3])
v1 = v.copy() # Copy by reference
v1[0]=10
print ('Value of v after v.copy() is modified is %s\n'%v)

Value of v, after v1 is modified is [10  2  3]

Value of v after func(v) is modified is [10  2  3]

Value of v after v.copy() is modified is [1 2 3]



#### 1.4.2 Experiment : Change the value of matrices by Reference

In [17]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print ('Original Matrix is \n%s\n'%mat)

#1 Add 10 to all the even indexes in matrix
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat1 = mat[::2,::2]
mat1+=10
print (' Matrix with 10 added to even indices is \n%s\n'%mat1)
# Changes in mat1 are reflected in mat. This happens because the default assignment in numpy is 'pass by reference'

Original Matrix is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Matrix with 10 added to even indices is 
[[11 13]
 [17 19]]



> **Note :** mat1+=10 is different from mat1=mat1+10, as a new space is allocated for mat1 in the latter case.

## 1.5 Broadcast Operation in Numpy
Broadcast Operation is like a razor-sharp knife, to be used with great care. It is a way to ***broadcast*** data of lower or same  dimension onto another ndarray. It is similar to ***map*** operation in python, scala, hadoop.  Broadcast rules are not limited to 2D array. There are extremely specific set of rules for nd-array broadcasting. You can visit ***[numpy documentation on broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)*** to get the complete picture. However, we will be restricting the discussion to only 2D-matrices.



In [18]:
mat = np.random.randint(0,6,(3,5))
print ('mat is \n%s\n'%mat)
v = np.array([10,20,30,40,50])
print ('v is \n%s\n'%v)
print ('mat+1 is \n%s\n'%(mat+1)) # Similar behaviour in case of np.array([1])
print ('mat+v is \n%s\n'%(mat+v))
print ('mat*v is \n%s\n'%(mat*v))
print ('mat+mat is \n%s\n'%(mat+mat))
print ('mat*mat is \n%s\n'%(mat*mat))


mat is 
[[1 2 3 4 3]
 [3 1 0 0 4]
 [3 1 2 2 0]]

v is 
[10 20 30 40 50]

mat+1 is 
[[2 3 4 5 4]
 [4 2 1 1 5]
 [4 2 3 3 1]]

mat+v is 
[[11 22 33 44 53]
 [13 21 30 40 54]
 [13 21 32 42 50]]

mat*v is 
[[ 10  40  90 160 150]
 [ 30  20   0   0 200]
 [ 30  20  60  80   0]]

mat+mat is 
[[2 4 6 8 6]
 [6 2 0 0 8]
 [6 2 4 4 0]]

mat*mat is 
[[ 1  4  9 16  9]
 [ 9  1  0  0 16]
 [ 9  1  4  4  0]]



## 1.6 Matrix Operations 
There are two major matix Operations which are important for us.
1. Inner Product
  * Vector Vector
  * Matrix Vector 
  * Matrix Matrix
2. Outer product

#### 1.6.1 Inner Product
In terms of Inner Product or Dot product, <v,w> will be be nothing but sum of element wise product.
$$<v,w> = \sum v_i*w_i = \begin{bmatrix} v_0 & v_1 & \cdots & v_n \end{bmatrix}\begin{bmatrix} w_0 \\ w_1 \\ \cdots \\ w_n \end{bmatrix}$$
So, the dot product between vector $v=[1,2,3]$ and  $w=[2,4,6]$ will be 
$$\begin{align}1*2 + 2*4 + 3*6 \\ 2+8+18 \\ 28\end{align}$$  
We will be covering matrix matrix multiplication in much depth in next-to-next chapter, but you can take it for granted as of now.
#### 1.6.2 Outer Product
The **outer product** on other end is 
$$\begin{bmatrix} v_0 \\ v_1 \\ \cdots \\ v_n \end{bmatrix}\begin{bmatrix} w_0 & w_1 & \cdots & w_n \end{bmatrix} = \begin{bmatrix}v_0w_0 & \cdots & v_0w_j & \cdots & v_0w_n \\ \vdots && \vdots && \vdots \\ v_iw_0 & \cdots & v_iw_j & \cdots & v_iw_n \\ \vdots && \vdots && \vdots \\ v_nw_0 & \cdots & v_nw_j & \cdots & v_nw_n    \end{bmatrix} $$

In [19]:
mat = np.arange(9).reshape(3,3)
vec1 = np.array([1,2,3])
vec2 = np.array([2,4,6])
print ('Vector v1 is %s\n'%vec1)
print ('Vector v2 is %s\n'%vec2)
print ('Vector Vector dot product is <v1,v2> is %s\n'%np.dot(vec1,vec2))
print ('---------------\n')

print ('Matrix is\n%s\n'%mat)
print ('Vector v2 is\n%s\n'%vec1)

print ('Matrix Vector product is <mat,vec1> is \n%s\n'%np.dot(mat,vec1))
print ('Matrix Matrix multiplication is <mat,mat> is \n%s\n'%np.dot(mat,mat))
print ('---------------\n')

print ('Vector v1 is %s\n'%vec1)
print ('Vector v2 is %s\n'%vec2)
print ('Vector Vector outer product is <v1,v2> is \n%s\n'%np.outer(vec1,vec2))


Vector v1 is [1 2 3]

Vector v2 is [2 4 6]

Vector Vector dot product is <v1,v2> is 28

---------------

Matrix is
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Vector v2 is
[1 2 3]

Matrix Vector product is <mat,vec1> is 
[ 8 26 44]

Matrix Matrix multiplication is <mat,mat> is 
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

---------------

Vector v1 is [1 2 3]

Vector v2 is [2 4 6]

Vector Vector outer product is <v1,v2> is 
[[ 2  4  6]
 [ 4  8 12]
 [ 6 12 18]]



## 1.7 Statistical Functions
1. **np.mean**(data,axis=0)
2. **np.var**(data,axis=0)
3. **np.sum**(data,axis=0)
4. **np.max**(data,axis=0)
5. **np.min**(data,axis=0)
6. **np.percentile**(data, percentage,axis=0)

In [20]:

mat = np.arange(9).reshape((3,3))
print ('Original matrix is \n%s\n'%mat)
print ('Overall mean of matrix is \n%s\n'%np.mean(mat))
print ('Row mean of matrix is \n%s\n'%np.mean(mat, axis=0))
print ('Column mean of matrix is \n%s\n'%np.mean(mat, axis=1))
print ('---------------------------\n')
print ('Overall varience of matrix is %s\n'%np.var(mat))
print ('Overall sum of matrix is %s\n'%np.sum(mat))
print ('Overall min of matrix is %s\n'%np.min(mat))
print ('Overall max of matrix is %s\n'%np.max(mat))

print ('-------------------------------------\n')
marks = np.array([30,31,32,40,90,95,97,98,99,100])
print ('Marks = %s\n'%marks)
print ('Overall 30 percent quantile of marks is %s\n'%(str(np.percentile(marks,30))))


Original matrix is 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Overall mean of matrix is 
4.0

Row mean of matrix is 
[3. 4. 5.]

Column mean of matrix is 
[1. 4. 7.]

---------------------------

Overall varience of matrix is 6.666666666666667

Overall sum of matrix is 36

Overall min of matrix is 0

Overall max of matrix is 8

-------------------------------------

Marks = [ 30  31  32  40  90  95  97  98  99 100]

Overall 30 percent quantile of marks is 37.599999999999994



## 1.8 Miscellenous Functions
In this section, we will be discussing some important miscellenous Functions which come in handy for matrix manipulation.
#### 1.8.1 squeeze
numpy.**squeeze**(a,axis=None)  
This function tries to reduce the excess dimensions which have only 1 element. If we print the shape of the ndary, these excess dimension will have a 1 in that particular dimension's index. For example, a nd-matrix with shape (1,2,3,1), has $0^{th}$ and $3^{rd}$ dimension as excess.

In [21]:
ndmat = np.zeros(shape=(1,2,3,3,1))
print ('Original Shape of ndmat is %s\n'%str(ndmat.shape))
ndmat1 = np.squeeze(ndmat)
print ('Shape of np.squeeze(ndmat) is %s\n'%str(ndmat1.shape))



Original Shape of ndmat is (1, 2, 3, 3, 1)

Shape of np.squeeze(ndmat) is (2, 3, 3)



#### 1.8.2 transpose
numpy.**transpose**(a, *axes=None*)  
This function reverses the axes for 2D array.  
For multidimensional array, it permutes the matrix according to the axis argument

In [22]:
mat = np.zeros(shape=(2,3))
print ('Original Shape of 2D matrix is %s\n'%str(mat.shape))
mat_transpose = np.transpose(mat)
print ('Shape of np.transpose(mat) is %s\n'%str(mat_transpose.shape))
mat_transpose[1,0] = 1
print ('np.transpose is by yet again assignment by reference, as changes in transpose reflects in the original matrix\n')
print ('---------------------------------\n')
# NDimensional matrix
ndmat = np.zeros(shape=(2,3,4))
print ('Original Shape of nDimensional matrix is %s\n'%str(ndmat.shape))
ndmat_transpose = np.transpose(ndmat)
print ('Shape of np.transpose(ndmat) is %s\n'%str(ndmat_transpose.shape))
ndmat_special_transpose = np.transpose(ndmat, axes = [0,2,1])
print ('Shape of np.transpose(ndmat, axes=[0,2,1]) is %s\n'%str(ndmat_special_transpose.shape))


Original Shape of 2D matrix is (2, 3)

Shape of np.transpose(mat) is (3, 2)

np.transpose is by yet again assignment by reference, as changes in transpose reflects in the original matrix

---------------------------------

Original Shape of nDimensional matrix is (2, 3, 4)

Shape of np.transpose(ndmat) is (4, 3, 2)

Shape of np.transpose(ndmat, axes=[0,2,1]) is (2, 4, 3)



# Chapter 1 Assignment
1. Create a null array of size 10 but the fifth value which is 1
2. Reverse a above created array (first element becomes last)
3. Create a 3x3 matrix with values ranging from 0 to 8
4. Find indices of non-zero elements from [1,2,0,0,4,0]
5. Create a 3x3x3 array with random values
6. Create a 10x10 array with random values and find the minimum and maximum values
7. Create a random vector of size 30 and find the mean value
8. Create a 2d array with 1 on the border and 0 inside
9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
10. Extract the integer part of a random array
11. Create a 5x5 matrix with row values ranging from 0 to 4
12. Create a random vector of size 10 and sort it
13. Consider two random array A anb B, check if they are equal
14. How to tell if a given 2D array has null columns?
15. Considering a four dimensions array, how to get sum over the last two axis at once?
16. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [25]:
#1 - 1. Create a null array of size 10 but the fifth value which is 1
#Null array - An array of all zeros 
#BUT the 5th value is 1 

arr = np.zeros(10)
arr[4] = 1
print(arr)

#Remember that for numpy the index starts at 0

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [26]:
#2 - 2. Reverse a above created array (first element becomes last)
#[start]:[end]:[jump]
arr_reversed = arr[::-1]
print(arr_reversed)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [27]:
#3 - 3. Create a 3x3 matrix with values ranging from 0 to 8
#np.arange(9) gives values 0 up to (but not including) 9 - so 0 through 8 
#numpy arrays have a .reshape() method that rearranges a flat array into a given shapte
number3 = np.arange(9).reshape(3,3)
print(number3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
#4 - 4. Find indices of non-zero elements from [1,2,0,0,4,0]
#numpy.nonzero(array) scans through the array and returns the indices where the value is anything 
#other than zero 
number4arr = np.array([1,2,0,0,4,0])
number4idx = np.nonzero(number4arr)[0]
print(number4idx)

#np.nonzero() returns a tuple with 1 array inside 
#[0] says give me the first item in the tuple, which is the array of indices 

[0 1 4]


In [74]:
#5 - 5. Create a 3x3x3 array with random values
number5arr = np.random.random((3, 3, 3))
print(number5arr)


[[[0.99609779 0.36465148 0.31208805]
  [0.53889881 0.05521981 0.07851922]
  [0.76125786 0.32682723 0.28724305]]

 [[0.08466946 0.03649193 0.46287679]
  [0.29940139 0.90730096 0.19100415]
  [0.98016682 0.37735282 0.86111184]]

 [[0.73647208 0.4954228  0.98527787]
  [0.47328854 0.90893923 0.46182821]
  [0.79203204 0.17833978 0.27017471]]]


In [34]:
#6 - 6. Create a 10x10 array with random values and 
#find the minimum and maximum values
number6arr = np.random.random(size = (10,10))
print(number6arr)

#Finding the minimum and maximum values:

print('Minimum value:', np.min(number6arr))
print('Maximum value:', np.max(number6arr))



[[0.38646144 0.11956269 0.04140154 0.44280709 0.81911642 0.22621671
  0.24481517 0.20385301 0.9491832  0.47156716]
 [0.55535187 0.20633662 0.65364213 0.444099   0.49876531 0.34389253
  0.68517755 0.30911507 0.50800042 0.39614497]
 [0.78415603 0.77327305 0.5557606  0.31480873 0.77505988 0.33450411
  0.64297014 0.10496129 0.01982668 0.31013282]
 [0.86973735 0.41129794 0.55882972 0.24704452 0.27203453 0.67948533
  0.464761   0.61234947 0.2325546  0.21375221]
 [0.24752488 0.0311721  0.95155335 0.07362955 0.20348053 0.41440633
  0.46413186 0.12964152 0.6795388  0.2324832 ]
 [0.72271561 0.9341448  0.01751472 0.26650963 0.06550237 0.39171039
  0.69037867 0.24706618 0.35872366 0.21003427]
 [0.60267772 0.18337641 0.85545733 0.49008563 0.95953533 0.84291729
  0.86406789 0.7099785  0.52931242 0.6734064 ]
 [0.7674448  0.18295484 0.61377188 0.58591501 0.24607635 0.55689133
  0.73895658 0.68263956 0.53845831 0.94331787]
 [0.35030973 0.06102513 0.06273448 0.39954888 0.15985267 0.5241247
  0.7558209  

In [35]:
#7 - 7. Create a random vector of size 30 and find the mean value

number7vec = np.random.random(size = 30)
print(number7vec)
print('Vector Mean Value:', np.mean(number7vec))

[0.37184668 0.20996043 0.95549905 0.17188494 0.30125755 0.33232772
 0.76366505 0.87208479 0.4544116  0.48633714 0.15610089 0.38413012
 0.75925281 0.88748633 0.22775411 0.99112683 0.2214434  0.2825396
 0.03739596 0.96826718 0.52516016 0.73656182 0.29001207 0.22621378
 0.23776915 0.06726577 0.00461354 0.69744365 0.4705792  0.25503045]
Vector Mean Value: 0.44484739263154016


In [36]:
#8 - 8. Create a 2d array with 1 on the border and 0 inside
number8arr = np.ones((4,4))
number8arr[1:-1, 1:-1] = 0 
print(number8arr)



[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [73]:
#9 - 9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

A = np.random.randint(0,10, size = (5,3))
B = np.random.randint(0,10, size = (3,2))
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)


result = A @ B
print("Multiplying a 5x3 matrix by a 3x2 matrix:")
print(result)


Matrix A:
[[6 8 0]
 [7 8 4]
 [9 6 6]
 [6 1 7]
 [9 4 2]]
Matrix B:
[[9 3]
 [4 8]
 [5 3]]
Multiplying a 5x3 matrix by a 3x2 matrix:
[[ 86  82]
 [115  97]
 [135  93]
 [ 93  47]
 [107  65]]


In [41]:
#10 - 10. Extract the integer part of a random array

number10arr = np.random.random(size = 10) * 10
#print(number10arr)
integer_part = number10arr.astype(int)
print(integer_part)

[9 2 9 5 1 5 2 4 3 7]


In [42]:
#11 - 11. Create a 5x5 matrix with row values ranging from 0 to 4
number11arr = np.arange(5) # [0,1,2,3,4]
result = np.tile(number11arr, (5,1))
print(result)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [44]:
#12 - 12. Create a random vector of size 10 and sort it

num12vec = np.random.random(size = 10)
print("Unsorted:", num12vec)

sortednum12vec = np.sort(num12vec)
print("Sorted:", sortednum12vec)

Unsorted: [0.6875211  0.73317953 0.55762938 0.10482058 0.33708897 0.36090086
 0.88772693 0.73338676 0.95722043 0.70746077]
Sorted: [0.10482058 0.33708897 0.36090086 0.55762938 0.6875211  0.70746077
 0.73317953 0.73338676 0.88772693 0.95722043]


In [47]:
#13 - 13. Consider two random array A anb B, check if they are equal

#Need to create an array
num13arrA = np.random.randint(0,10,5)
num13arrB = np.random.randint(0,10,5)
print(num13arrA) #Printing A and B
print(num13arrB)
print(np.array_equal(num13arrA, num13arrB)) #This checks if they are equal



[2 8 0 2 5]
[5 0 7 9 2]
False


In [49]:
#14 - 14. How to tell if a given 2D array has null columns?

#Well a null column is a column where every value is 0
#We can check for null comuns using np.all()
#np.all tells us column by column whether each one is entirely
#zeros (True) or not (False)

num14arr = np.array([[6,7,0],
                      [6,7,0],
                      [6,7,0]])
print(num14arr)

has_null_columns = np.all(num14arr == 0, axis = 0)
print('Null columns (If True = Is a Null Column):', has_null_columns)



[[6 7 0]
 [6 7 0]
 [6 7 0]]
Null columns (If True = Is a Null Column): [False False  True]


In [53]:
#15 - 15. 15. Considering a four dimensions array,
#how to get sum over the last two axis at once?

#First need to create a random 4D array 
num15arr = np.random.randint(0,10, size = (2,3,4,5))

#Then we need to sum over the last two axes 
num15result = np.sum(num15arr, axis = (-2,-1)) #This tells NUMPY to 
#sum over the last two dimensions of the array


print("Original 4D array:")
print(num15arr)

print("\nSum over the last two axes:")
print(num15result)


Original 4D array:
[[[[5 6 9 9 8]
   [1 4 3 2 2]
   [9 7 6 8 7]
   [3 5 6 3 6]]

  [[2 9 9 4 4]
   [1 1 9 3 9]
   [7 8 0 0 0]
   [0 6 6 8 2]]

  [[6 5 5 1 4]
   [4 1 7 2 1]
   [1 5 0 6 5]
   [1 9 5 8 9]]]


 [[[1 7 9 1 2]
   [8 6 6 3 8]
   [4 7 5 2 9]
   [5 8 1 5 5]]

  [[1 3 0 1 2]
   [2 8 5 7 2]
   [6 6 1 8 1]
   [9 2 4 6 8]]

  [[1 0 2 4 2]
   [7 7 8 5 3]
   [6 8 8 7 9]
   [2 9 1 9 6]]]]

Sum over the last two axes:
[[109  88  85]
 [102  82 104]]


In [62]:
#16 - 16. Consider an array of dimension (5,5,3),
#how to mulitply it by an array with dimensions (5,5)

#Trying to multiply an array of dimension (5,5,3) with an array with dimensions(5,5)
#will fail because numpy's broadcasting rules compare shpes from the right side
#and (5,5,3) vs (5,5) don't line up 

#Trying to multipl them directly with result in a ValueError

num16arrA = np.random.randint(0, 10, size=(5,5,3))
num16arrB =np.random.randint(0, 10, size=(5,5))

#num16result = A * B #This will error

#But it is possible to multiply them
#We need to reshape B so numpy knows how to line it up
#We need to add an extra dimension of size 1 at the end
num16arrBres = num16arrB[:, :, np.newaxis]
num16resultreshaped = num16arrA * num16arrBres
print(num16resultreshaped)





[[[ 0 18 18]
  [ 0  5  8]
  [81  9  9]
  [18  6  2]
  [ 0  0  0]]

 [[ 0  1  4]
  [32 56 24]
  [ 0  0 21]
  [48  6 36]
  [27 72 63]]

 [[ 7  0  8]
  [36 81  0]
  [24 28  8]
  [ 8 14 12]
  [ 6  6 24]]

 [[14  8  8]
  [14 35 42]
  [ 6  9  2]
  [ 0 18  9]
  [40 40 15]]

 [[12 28 16]
  [ 0  0  0]
  [ 9  0 27]
  [20 12 24]
  [32 16 16]]]


In [64]:
#17 - 17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

num17arr = np.random.randint(0,10, (10,10))

#Need to extract all contiguous 3 x 3 blocks
blocks = sliding_window_view(num17arr, (3,3))

#Print the original 10x10 matrix
print("Original 10x10 matrix:")
print(num17arr)

#Print all 3 x 3 contiguous blocks
print(blocks)

Original 10x10 matrix:
[[6 1 0 3 8 8 6 4 5 7]
 [1 6 8 8 0 6 5 2 2 6]
 [8 6 6 9 4 4 6 9 4 2]
 [2 3 6 2 9 2 3 9 8 8]
 [6 0 0 5 9 6 9 4 2 2]
 [7 9 3 9 1 8 6 0 3 2]
 [0 3 5 6 5 2 1 6 9 5]
 [6 7 2 3 7 1 6 9 7 0]
 [5 6 8 7 6 0 1 4 5 0]
 [6 4 0 3 6 1 6 9 7 4]]
[[[[6 1 0]
   [1 6 8]
   [8 6 6]]

  [[1 0 3]
   [6 8 8]
   [6 6 9]]

  [[0 3 8]
   [8 8 0]
   [6 9 4]]

  [[3 8 8]
   [8 0 6]
   [9 4 4]]

  [[8 8 6]
   [0 6 5]
   [4 4 6]]

  [[8 6 4]
   [6 5 2]
   [4 6 9]]

  [[6 4 5]
   [5 2 2]
   [6 9 4]]

  [[4 5 7]
   [2 2 6]
   [9 4 2]]]


 [[[1 6 8]
   [8 6 6]
   [2 3 6]]

  [[6 8 8]
   [6 6 9]
   [3 6 2]]

  [[8 8 0]
   [6 9 4]
   [6 2 9]]

  [[8 0 6]
   [9 4 4]
   [2 9 2]]

  [[0 6 5]
   [4 4 6]
   [9 2 3]]

  [[6 5 2]
   [4 6 9]
   [2 3 9]]

  [[5 2 2]
   [6 9 4]
   [3 9 8]]

  [[2 2 6]
   [9 4 2]
   [9 8 8]]]


 [[[8 6 6]
   [2 3 6]
   [6 0 0]]

  [[6 6 9]
   [3 6 2]
   [0 0 5]]

  [[6 9 4]
   [6 2 9]
   [0 5 9]]

  [[9 4 4]
   [2 9 2]
   [5 9 6]]

  [[4 4 6]
   [9 2 3]
   [9 6 9]]

  [[4 6

In [66]:
#18 - 18. Consider a 16x16 array,
#how to get the block-sum (block size is 4x4)?


num18arr = np.random.randint(0,10,(16,16))
#Need to reshape int sixteen 4v4 blocks and sum each block
block_sum = num18arr.reshape(4,4,4,4).sum(axis = (1,3))
#Here's the original array 
print("Original 16x16 array")
print(num18arr)

#Then printing the block sums
print("Block sums:")
print(block_sum)



Original 16x16 array
[[3 9 0 7 3 8 1 0 9 5 9 9 7 6 5 0]
 [4 8 5 4 2 9 7 9 2 2 3 4 1 9 9 5]
 [3 5 5 3 3 8 2 2 2 1 8 9 2 6 7 1]
 [0 9 5 5 2 3 9 8 1 3 5 3 4 8 1 9]
 [9 4 2 0 4 6 4 9 7 6 9 1 1 7 4 3]
 [9 7 9 1 6 4 8 8 0 7 1 5 4 4 7 9]
 [6 7 4 0 5 5 2 9 7 1 4 6 2 9 6 0]
 [8 1 1 0 1 3 6 7 1 0 2 8 9 4 8 3]
 [6 4 1 2 0 2 0 5 9 7 0 4 8 9 9 3]
 [3 7 9 6 3 0 2 8 6 9 0 4 6 3 6 4]
 [5 4 0 7 3 4 2 9 5 5 5 0 5 8 2 6]
 [1 1 6 4 0 6 0 2 2 0 6 2 6 7 4 8]
 [4 0 9 4 2 5 9 7 0 1 2 0 4 0 1 9]
 [8 0 1 4 4 3 5 4 7 4 3 7 8 6 7 3]
 [5 8 5 2 7 1 0 3 4 3 7 2 3 1 2 0]
 [8 9 7 9 6 7 9 7 4 0 7 2 9 2 4 7]]
Block sums:
[[75 76 75 80]
 [68 87 65 80]
 [66 46 64 94]
 [83 79 53 66]]
